"""
migration.py — turn an 'absorb' decision into an actionable plan.

For each repo to be absorbed into a hub it produces an ordered migration
checklist. Hybrid, like replan:
  * the configured LLM (via the failover chain) writes a checklist tailored to
    the repo's README + metadata and the hub's purpose, when available;
  * otherwise a deterministic template fills in from language/topics.

It also proposes a scaffold (one module dir per absorb) and composes a
MIGRATION.md the hub repo can carry.
"""
from __future__ import annotations

import logging
import re

log = logging.getLogger(__name__)


def slug(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def scaffold_for(hub: str, absorbs: list[str]) -> list[dict]:
    """Proposed target location for each absorbed repo inside the hub."""
    return [{"repo": r, "module": slug(r), "path": f"modules/{slug(r)}/"} for r in absorbs]


# --- rule template ---------------------------------------------------------

_LANG_DEP_HINT = {
    "Python": "merge requirements/pyproject deps; namespace under the package",
    "TypeScript": "merge package.json deps; expose as a workspace package",
    "JavaScript": "merge package.json deps; expose as a workspace package",
    "C#": "add as a project reference; reconcile NuGet packages",
    "Rust": "add as a workspace crate; merge Cargo deps",
    "Go": "add as an internal package; reconcile go.mod",
}


def _rule_checklist(repo: dict, hub: str) -> list[str]:
    name = repo["name"]
    lang = repo.get("language") or ""
    lang_phrase = f"{lang} " if lang else ""
    mod = slug(name)
    dep = _LANG_DEP_HINT.get(lang, "reconcile its dependencies into the hub build")
    age = (repo.get("pushed_at") or "")[:10]
    note = f" (last pushed {age}; {repo.get('stars', 0)}★)" if age else ""
    return [
        f"Review {name}{note} — skim its README and entrypoints; decide core vs. drop.",
        f"Create modules/{mod}/ in {hub} and move the core {lang_phrase}code there.",
        f"Dependencies: {dep}.",
        f"Wire {mod}'s entrypoint into {hub}'s API/CLI surface.",
        f"Port {name}'s tests; add a smoke test under {hub}.",
        f"Update {hub} README (mark {name} absorbed) and push.",
        f"Archive {name} on GitHub and mark it absorbed in git-suite.",
    ]


# --- LLM checklist ---------------------------------------------------------

async def _llm_checklist(repo: dict, hub_meta: dict, readme: str | None) -> list[str] | None:
    from services import llm
    if not llm.has_provider():
        return None
    try:
        prompt = f"""You are planning how to absorb a standalone GitHub repo into a larger "hub" repo.

Repo to absorb:
  name: {repo['name']}
  language: {repo.get('language') or 'unknown'}
  topics: {', '.join(repo.get('topics') or []) or 'none'}
  description: {repo.get('aim') or '(none)'}
  README excerpt:
  ---
  {(readme or '(no README)')[:1500]}
  ---

Destination hub: {hub_meta.get('name')} (Layer {hub_meta.get('layer')})
Hub purpose: {hub_meta.get('description')}
Hub boundary: {hub_meta.get('boundary') or '(none)'}

Write a concrete, ordered migration checklist (5-9 steps) to fold this repo's
useful functionality into the hub. Be specific to THIS repo — reference its
actual capabilities. Each step is one imperative sentence.

Return ONLY a JSON array of strings, no markdown."""
        steps = await llm.complete_json(prompt, max_tokens=700)
        if isinstance(steps, list) and steps:
            return [str(s) for s in steps]
    except Exception as exc:
        log.warning("LLM checklist failed for %s: %s", repo.get("name"), exc)
    return None


async def checklist_for(repo: dict, hub_meta: dict, readme: str | None) -> dict:
    """Return {steps, source} — LLM-tailored if possible, else a rule template."""
    steps = await _llm_checklist(repo, hub_meta, readme)
    if steps:
        return {"steps": steps, "source": "llm"}
    return {"steps": _rule_checklist(repo, hub_meta.get("name", "")), "source": "rule"}


def build_migration_md(hub: str, hub_meta: dict, items: list[dict]) -> str:
    """Compose a MIGRATION.md for the hub from per-repo checklists.

    items: [{repo, module, path, live, done, steps}]
    """
    lines = [
        f"# {hub} — Migration Plan",
        "",
        f"**Layer {hub_meta.get('layer', '?')} — {hub_meta.get('description', hub)}**",
        "",
        "Generated by git-suite. Each section folds a standalone repo into this hub.",
        "",
        "## Target structure",
        "```",
        f"{hub}/",
        "  modules/",
    ]
    for it in items:
        lines.append(f"    {it['module']}/   # from {it['repo']}")
    lines += ["```", ""]
    for it in items:
        status = "done" if it.get("done") else ("ready" if it.get("live") else "not on GitHub")
        lines.append(f"## {it['repo']}  → `{it['path']}`  ({status})")
        steps = it.get("steps") or []
        if steps:
            lines += [f"{i}. {s}" for i, s in enumerate(steps, 1)]
        else:
            lines.append("_No checklist generated yet._")
        lines.append("")
    return "\n".join(lines)
